### ISSUE TITLE
文档解析功能返回401

### ISSUE THREAD

**Issue by lyxwest** [baidubce/app-builder#19]
文档解析在使用手册中是免费使用的，但我使用示例代码进行文档解析，返回权限错误。这是什么原因呢？而我使用同样的API KEY进行TTS是可以正常返回结果的。
以下是具体报错信息：
Traceback (most recent call last):
  File "/home/yxliu56/code/work/app-builder/docprase.py", line 42, in <module>
    parse_result = parser(msg, return_raw=True)
  File "/home/yxliu56/code/work/app-builder/appbuilder/core/component.py", line 94, in __call__
    return self.run(*inputs, **kwargs)
  File "/home/yxliu56/code/work/app-builder/appbuilder/core/components/doc_parser/doc_parser.py", line 126, in run
    self.check_response_header(response)
  File "/home/yxliu56/code/work/app-builder/appbuilder/core/component.py", line 149, in check_response_header
    raise BaseRPCException(message)
appbuilder.core._exception.BaseRPCException: request_id=30d05399-ea69-4b10-93be-0dcebb70e255 , http status code is 401, body is {"requestId":"30d05399-ea69-4b10-93be-0dcebb70e255","code":216003,"message":"Authentication error: ( Unsupported authorization header type )"}

以下是我的调用代码
`import os
os.environ["APPBUILDER_TOKEN"] = "我的百度apikey，是复制的SDK密钥中的API KEY"
from appbuilder.core.components.doc_parser.doc_parser import DocParser
from appbuilder.core.components.doc_splitter.doc_splitter import DocSplitter
from appbuilder.core.message import Message
# 进行文档内容解析
file_path = "text.pptx"  # 待解析的文件路径
msg = Message(file_path)
parser = DocParser()
parse_result = parser(msg)
print(parse_result.content)`

**Comment by sucuicong** [comment]
这个是因为token不正确导致的，请确认下token，正确的token使用示例应该是
